MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/wenli/.cache/torch/checkpoints/resnet101_ibn_b.pth'
  METRIC_LOSS_TYPE: 'triplet'  # default setting is triplet_center
  IF_LABELSMOOTH: 'off' # if use label smooth will raise score.
  IF_WITH_CENTER: 'no'
  NAME: 'resnet101_ibn_b'
  DEVICE_ID: ('0,1')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  POOLING_METHOD: 'GeM'
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True
  THRESH: 0.3
  IF_USE_PCB: False
  MERGE_PCB_FEAT: True
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.2 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('../data')
  HARD_AUG: True
  USE_UNLABEL: True
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 2
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  MAX_EPOCHS: 60
  BASE_LR: 0.01
  IMS_PER_BATCH: 224
  STEPS: [25, 40]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.003
  FP16: True

TEST:
  IMS_PER_BATCH: 60
  RE_RANKING: True
  WEIGHT: '/home/wenli/model/fs_weight/128/resnet101_ibn_b_40.pth' # ../model/0102-b-2_oral_300/resnet50_ibn_b_55.pth
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  USE_LOCAL: True
  PCB_GLOBAL_FEAT_ENSEMBLE: False
  USE_PCB_MERGE_FEAT: False
OUTPUT_DIR: "../model/rinb101_40weight_128"






