MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/wenli/.cache/torch/checkpoints/se_resnet50_ibn_a.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'se_resnet50_ibn_a'
  DEVICE_ID: ('0,1')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 0.1
  TRIPLET_LOSS_WEIGHT: 0.9
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True
  THRESH: 0.45
  IF_USE_PCB: False
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('../data')
  HARD_AUG: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 2
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  MAX_EPOCHS: 60
  BASE_LR: 0.01
  IMS_PER_BATCH: 200
  STEPS: [25, 40]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.003
  FP16: True

TEST:
  IMS_PER_BATCH: 200
  RE_RANKING: True
  WEIGHT: '../model/fs_buff_all_data_se_50/se_resnet50_ibn_a_50.pth' # ../model/fs_buff_all_data_se_50/se_resnet50_ibn_a_50.pth
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  USE_LOCAL: True
OUTPUT_DIR: "../model/fs_buff_all_data_se_50/"


